# -*- coding: utf-8 -*-
"""PlotGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O41BsTYVoypQw8y99vD85kg4-nGHNiKf
"""

!git clone https://github.com/harshitadd/gpt-2.git
import os 
os.chdir('gpt-2')
!sh download_model.sh 117M 
!pip3 install -r requirements.txt

!python3 src/interactive_conditional_samples.py --top_k 40